name: PHPStan

on:
  push:
    branches:
      - main
      - "*.x"
  pull_request:

permissions:
  contents: read

env:
  phpv: 8.2

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: ${{ env.phpv }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
